version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: os_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: os_manager
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  task-service:
    build: ./task-service
    ports:
      - "3001:3001"
    depends_on:
      - db

  auth-service:
    build: ./auth-service
    ports:
      - "3002:3002"

volumes:
  db_data:
